import { TextKey } from './text-keys'

export const EnglishTextKey = {
    [TextKey.AlreadyHaveAnAccount]: 'Already have an account?',
    [TextKey.DisplayName]: 'Display name',
    [TextKey.Email]: 'Email',
    [TextKey.FirstName]: 'First name',
    [TextKey.GoogleSignUp]: 'Sign in with Google',
    [TextKey.LastName]: 'Last name',
    [TextKey.Loading]: 'Loading',
    [TextKey.NoAccountYet]: 'Not having an account yet?',
    [TextKey.Password]: 'Password',
    [TextKey.SignIn]: 'Sign in',
    [TextKey.SignUp]: 'Sign up',
    [TextKey.RecipeName]: 'Recipe name',
    [TextKey.RecipeDescription]: 'Description',
    [TextKey.RecipeServingsNumber]: 'Number of servings',
    [TextKey.DurationCooking]: 'Cooking duration',
    [TextKey.DurationPreparation]: 'Preparation duration',
    [TextKey.Save]: 'Save',
    [TextKey.SectionName]: 'Section name',
    [TextKey.SectionDescription]: 'Description',
    [TextKey.DeleteSection]: 'Delete section',
    [TextKey.AddSection]: 'Add new section',
    [TextKey.IngredientName]: 'Ingredient name',
    [TextKey.IngredientAmount]: 'Amount',
    [TextKey.IngredientUnit]: 'Units',
    [TextKey.AddIngredient]: 'Add ingredient',
    [TextKey.MakePublic]: 'Make recipe public for other users',
}
