export const TextKey = {
    AlreadyHaveAnAccount: 'AlreadyHaveAnAccount',
    DisplayName: 'DisplayName',
    Email: 'Email',
    FirstName: 'FirstName',
    GoogleSignUp: 'GoogleSignUp',
    LastName: 'LastName',
    Loading: 'Loading',
    NoAccountYet: 'NoAccountYet',
    Password: 'Password',
    SignIn: 'SignIn',
    SignUp: 'SignUp',
    RecipeName: 'RecipeName',
    RecipeDescription: 'RecipeDescription',
    RecipeServingsNumber: 'RecipeServingsNumber',
    DurationCooking: 'CookingDuration',
    DurationPreparation: 'Preparation duration',
    Save: 'Save',
    SectionName: 'SectionName',
    SectionDescription: 'SectionDescription',
    DeleteSection: 'DeleteSection',
    AddSection: 'AddSection',
    IngredientName: 'IngredientName',
    IngredientAmount: 'IngredientAmount',
    IngredientUnit: 'IngredientUnit',
    AddIngredient: 'AddIngredient',
}
