name: Update production

on:
  push:
    branches:
      - develop

jobs:
  update-production:
    name: Merge develop into main after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: "develop"
          target: "main"
